version: '3'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pg
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=bookstore
    ports:
      - 5432:5432
    volumes:
      - bookstore_pgdata:/var/lib/postgresql/data
volumes:
  bookstore_pgdata: