# Generated by Django 4.1.7 on 2023-04-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='book',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
